### ISSUE TITLE
Demo app fails with a 404 unless user is logged in

### ISSUE THREAD

**Issue by davewsmith** [GoogleCloudPlatform/appengine-blobstore-python#3]
The demo fails with a 404 unless the user is logged in, but the requirement to log in isn't surfaced.

See http://stackoverflow.com/questions/31887028/error-404-when-image-is-uploaded-to-blob-store-while-working-locally for an example of this affecting a new user.

The proximate problem is

```
user=users.get_current_user().user_id()
```

which will raise an exception when users.get_current_user() returns None for a non-logged-in user. This is complicated by

```
except:
    self.redirect('/upload_failure.html')
```

which attempts to redirect to a non-existent file and masks the problem as a 404.

I'll submit a pull request that resolves both issues.

**Comment by jeffmendoza** [comment]
Thanks for the report @davewsmith, Yes, a PR would be great. Be sure to sign the CLA, as described in [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/appengine-blobstore-python/blob/master/CONTRIBUTING.md)

**Comment by davewsmith** [comment]
Both done. Sorry for the delay. I was away for a week.
